"""Jarvis PC apps plugin — registration."""
from . import (
    brain_api,
    browser_actions,
    calendar_api,
    chatgpt_actions,
    chrome_research,
    composio_api,
    connector_api,
    docs_actions,
    gmail_actions,
    google_workspace_api,
    handwriting_api,
    maps_api,
    memory_api,
    notebooklm_actions,
    page_look,
    phone_apps,
    ratings_api,
    schemas,
    site_browse,
    tools,
    web_find,
)


def register(ctx):
    ctx.register_tool(
        name="open_pc_app",
        toolset="pc_apps",
        schema=schemas.OPEN_PC_APP,
        handler=tools.open_pc_app,
    )
    ctx.register_tool(
        name="list_pc_apps",
        toolset="pc_apps",
        schema=schemas.LIST_PC_APPS,
        handler=tools.list_pc_apps,
    )
    ctx.register_tool(
        name="open_phone_app",
        toolset="pc_apps",
        schema=schemas.OPEN_PHONE_APP,
        handler=phone_apps.open_phone_app,
    )
    ctx.register_tool(
        name="list_phone_apps",
        toolset="pc_apps",
        schema=schemas.LIST_PHONE_APPS,
        handler=phone_apps.list_phone_apps,
    )
    ctx.register_tool(
        name="remember_fact",
        toolset="pc_apps",
        schema=schemas.REMEMBER_FACT,
        handler=memory_api.remember_fact,
    )
    ctx.register_tool(
        name="list_memories",
        toolset="pc_apps",
        schema=schemas.LIST_MEMORIES,
        handler=memory_api.list_memories,
    )
    ctx.register_tool(
        name="forget_memory",
        toolset="pc_apps",
        schema=schemas.FORGET_MEMORY,
        handler=memory_api.forget_memory,
    )
    ctx.register_tool(
        name="handwriting_status",
        toolset="pc_apps",
        schema=schemas.HANDWRITING_STATUS,
        handler=handwriting_api.handwriting_status,
    )
    ctx.register_tool(
        name="handwriting_write",
        toolset="pc_apps",
        schema=schemas.HANDWRITING_WRITE,
        handler=handwriting_api.handwriting_write,
    )
    ctx.register_tool(
        name="google_docs_create",
        toolset="pc_apps",
        schema=schemas.GOOGLE_DOCS_CREATE,
        handler=docs_actions.google_docs_open_and_type,
    )
    ctx.register_tool(
        name="google_slides_create",
        toolset="pc_apps",
        schema=schemas.GOOGLE_SLIDES_CREATE,
        handler=docs_actions.google_slides_open_and_type,
    )
    ctx.register_tool(
        name="google_docs_chrome_type",
        toolset="pc_apps",
        schema=schemas.GOOGLE_DOCS_CHROME_TYPE,
        handler=docs_actions.google_docs_open_and_type,
    )
    ctx.register_tool(
        name="google_slides_chrome_type",
        toolset="pc_apps",
        schema=schemas.GOOGLE_SLIDES_CHROME_TYPE,
        handler=docs_actions.google_slides_open_and_type,
    )
    ctx.register_tool(
        name="google_slides_build_deck",
        toolset="pc_apps",
        schema=schemas.GOOGLE_SLIDES_BUILD_DECK,
        handler=docs_actions.google_slides_build_deck,
    )
    ctx.register_tool(
        name="whatsapp_open_chat",
        toolset="pc_apps",
        schema=schemas.WHATSAPP_OPEN_CHAT,
        handler=browser_actions.whatsapp_open_chat,
    )
    ctx.register_tool(
        name="call_contact",
        toolset="pc_apps",
        schema=schemas.CALL_CONTACT,
        handler=phone_apps.call_contact,
    )
    ctx.register_tool(
        name="gmail_send",
        toolset="pc_apps",
        schema=schemas.GMAIL_SEND,
        handler=gmail_actions.gmail_send,
    )
    ctx.register_tool(
        name="gmail_draft",
        toolset="pc_apps",
        schema=schemas.GMAIL_DRAFT,
        handler=gmail_actions.gmail_draft,
    )
    ctx.register_tool(
        name="gmail_inbox",
        toolset="pc_apps",
        schema=schemas.GMAIL_INBOX,
        handler=gmail_actions.gmail_inbox,
    )
    ctx.register_tool(
        name="gmail_read_mail",
        toolset="pc_apps",
        schema=schemas.GMAIL_READ_MAIL,
        handler=gmail_actions.gmail_read_mail,
    )
    ctx.register_tool(
        name="gmail_status",
        toolset="pc_apps",
        schema=schemas.GMAIL_STATUS,
        handler=gmail_actions.gmail_status,
    )
    ctx.register_tool(
        name="list_browser_tabs",
        toolset="pc_apps",
        schema=schemas.LIST_BROWSER_TABS,
        handler=page_look.list_browser_tabs,
    )
    ctx.register_tool(
        name="look_at_browser",
        toolset="pc_apps",
        schema=schemas.LOOK_AT_BROWSER,
        handler=page_look.look_at_browser,
    )
    ctx.register_tool(
        name="web_find",
        toolset="pc_apps",
        schema=schemas.WEB_FIND,
        handler=web_find.web_find,
    )
    ctx.register_tool(
        name="browse_website",
        toolset="pc_apps",
        schema=schemas.BROWSE_WEBSITE,
        handler=site_browse.browse_website,
    )
    ctx.register_tool(
        name="movie_ratings_lookup",
        toolset="pc_apps",
        schema=schemas.MOVIE_RATINGS_LOOKUP,
        handler=ratings_api.movie_ratings_lookup,
    )
    ctx.register_tool(
        name="chrome_google_search",
        toolset="pc_apps",
        schema=schemas.CHROME_GOOGLE_SEARCH,
        handler=chrome_research.chrome_google_search,
    )
    ctx.register_tool(
        name="chrome_type_in_page",
        toolset="pc_apps",
        schema=schemas.CHROME_TYPE_IN_PAGE,
        handler=chrome_research.chrome_type_in_page,
    )
    ctx.register_tool(
        name="chrome_navigate_active_tab",
        toolset="pc_apps",
        schema=schemas.CHROME_NAVIGATE_ACTIVE_TAB,
        handler=chrome_research.chrome_navigate_active_tab,
    )
    ctx.register_tool(
        name="chrome_open_research_tabs",
        toolset="pc_apps",
        schema=schemas.CHROME_OPEN_RESEARCH_TABS,
        handler=chrome_research.chrome_open_research_tabs,
    )
    ctx.register_tool(
        name="close_jarvis_tabs",
        toolset="pc_apps",
        schema=schemas.CLOSE_JARVIS_TABS,
        handler=browser_actions.close_jarvis_tabs,
    )
    ctx.register_tool(
        name="chatgpt_open",
        toolset="pc_apps",
        schema=schemas.CHATGPT_OPEN,
        handler=chatgpt_actions.chatgpt_open,
    )
    ctx.register_tool(
        name="chatgpt_draft",
        toolset="pc_apps",
        schema=schemas.CHATGPT_DRAFT,
        handler=chatgpt_actions.chatgpt_draft,
    )
    ctx.register_tool(
        name="chatgpt_send",
        toolset="pc_apps",
        schema=schemas.CHATGPT_SEND,
        handler=chatgpt_actions.chatgpt_send,
    )
    ctx.register_tool(
        name="chatgpt_status",
        toolset="pc_apps",
        schema=schemas.CHATGPT_STATUS,
        handler=chatgpt_actions.chatgpt_status,
    )
    ctx.register_tool(
        name="youtube_type_search",
        toolset="pc_apps",
        schema=schemas.YOUTUBE_TYPE_SEARCH,
        handler=browser_actions.youtube_type_search,
    )
    ctx.register_tool(
        name="youtube_pick_video",
        toolset="pc_apps",
        schema=schemas.YOUTUBE_PICK_VIDEO,
        handler=browser_actions.youtube_pick_video,
    )
    ctx.register_tool(
        name="vidbox_type_search",
        toolset="pc_apps",
        schema=schemas.VIDBOX_TYPE_SEARCH,
        handler=browser_actions.vidbox_type_search,
    )
    ctx.register_tool(
        name="whatsapp_status",
        toolset="pc_apps",
        schema=schemas.WHATSAPP_STATUS,
        handler=browser_actions.whatsapp_status,
    )
    ctx.register_tool(
        name="whatsapp_draft_to_recent",
        toolset="pc_apps",
        schema=schemas.WHATSAPP_DRAFT_TO_RECENT,
        handler=browser_actions.whatsapp_draft_to_recent,
    )
    ctx.register_tool(
        name="whatsapp_draft_to_contact",
        toolset="pc_apps",
        schema=schemas.WHATSAPP_DRAFT_TO_CONTACT,
        handler=browser_actions.whatsapp_draft_to_contact,
    )
    ctx.register_tool(
        name="whatsapp_send",
        toolset="pc_apps",
        schema=schemas.WHATSAPP_SEND,
        handler=browser_actions.whatsapp_send,
    )
    ctx.register_tool(
        name="classroom_pull_dues",
        toolset="pc_apps",
        schema=schemas.CLASSROOM_PULL_DUES,
        handler=browser_actions.classroom_pull_dues,
    )
    ctx.register_tool(
        name="classroom_open_class",
        toolset="pc_apps",
        schema=schemas.CLASSROOM_OPEN_CLASS,
        handler=browser_actions.classroom_open_class,
    )
    ctx.register_tool(
        name="classroom_find_material",
        toolset="pc_apps",
        schema=schemas.CLASSROOM_FIND_MATERIAL,
        handler=browser_actions.classroom_find_material,
    )
    ctx.register_tool(
        name="classroom_check",
        toolset="pc_apps",
        schema=schemas.CLASSROOM_CHECK,
        handler=browser_actions.classroom_check,
    )
    ctx.register_tool(
        name="calendar_list",
        toolset="pc_apps",
        schema=schemas.CALENDAR_LIST,
        handler=calendar_api.calendar_list,
    )
    ctx.register_tool(
        name="calendar_add",
        toolset="pc_apps",
        schema=schemas.CALENDAR_ADD,
        handler=calendar_api.calendar_add,
    )
    ctx.register_tool(
        name="calendar_delete",
        toolset="pc_apps",
        schema=schemas.CALENDAR_DELETE,
        handler=calendar_api.calendar_delete,
    )
    ctx.register_tool(
        name="calendar_set_schedule",
        toolset="pc_apps",
        schema=schemas.CALENDAR_SET_SCHEDULE,
        handler=calendar_api.calendar_set_schedule,
    )
    ctx.register_tool(
        name="calendar_delete_schedule",
        toolset="pc_apps",
        schema=schemas.CALENDAR_DELETE_SCHEDULE,
        handler=calendar_api.calendar_delete_schedule,
    )
    ctx.register_tool(
        name="notebooklm_query",
        toolset="pc_apps",
        schema=schemas.NOTEBOOKLM_QUERY,
        handler=notebooklm_actions.notebooklm_query,
    )
    ctx.register_tool(
        name="notebooklm_read_notes",
        toolset="pc_apps",
        schema=schemas.NOTEBOOKLM_READ_NOTES,
        handler=notebooklm_actions.notebooklm_read_notes,
    )
    ctx.register_tool(
        name="notebooklm_audio_overview",
        toolset="pc_apps",
        schema=schemas.NOTEBOOKLM_AUDIO_OVERVIEW,
        handler=notebooklm_actions.notebooklm_audio_overview,
    )
    ctx.register_tool(
        name="notebooklm_generate_guide",
        toolset="pc_apps",
        schema=schemas.NOTEBOOKLM_GENERATE_GUIDE,
        handler=notebooklm_actions.notebooklm_generate_guide,
    )
    ctx.register_tool(
        name="notebooklm_add_note",
        toolset="pc_apps",
        schema=schemas.NOTEBOOKLM_ADD_NOTE,
        handler=notebooklm_actions.notebooklm_add_note,
    )
    ctx.register_tool(
        name="notebooklm_list_notebooks",
        toolset="pc_apps",
        schema=schemas.NOTEBOOKLM_LIST_NOTEBOOKS,
        handler=notebooklm_actions.notebooklm_list_notebooks,
    )
    ctx.register_tool(
        name="notebooklm_status",
        toolset="pc_apps",
        schema=schemas.NOTEBOOKLM_STATUS,
        handler=notebooklm_actions.notebooklm_status,
    )
    ctx.register_tool(
        name="second_brain_add_idea",
        toolset="pc_apps",
        schema=schemas.SECOND_BRAIN_ADD_IDEA,
        handler=brain_api.second_brain_add_idea,
    )
    ctx.register_tool(
        name="second_brain_list_ideas",
        toolset="pc_apps",
        schema=schemas.SECOND_BRAIN_LIST_IDEAS,
        handler=brain_api.second_brain_list_ideas,
    )
    ctx.register_tool(
        name="second_brain_clear_ideas",
        toolset="pc_apps",
        schema=schemas.SECOND_BRAIN_CLEAR_IDEAS,
        handler=brain_api.second_brain_clear_ideas,
    )
    ctx.register_tool(
        name="second_brain_add_genre",
        toolset="pc_apps",
        schema=schemas.SECOND_BRAIN_ADD_GENRE,
        handler=brain_api.second_brain_add_genre,
    )
    ctx.register_tool(
        name="daily_briefing",
        toolset="pc_apps",
        schema=schemas.DAILY_BRIEFING,
        handler=brain_api.daily_briefing,
    )
    ctx.register_tool(
        name="connector_list",
        toolset="pc_apps",
        schema=schemas.CONNECTOR_LIST,
        handler=connector_api.connector_list,
    )
    ctx.register_tool(
        name="connector_query",
        toolset="pc_apps",
        schema=schemas.CONNECTOR_QUERY,
        handler=connector_api.connector_query,
    )
    ctx.register_tool(
        name="connector_read",
        toolset="pc_apps",
        schema=schemas.CONNECTOR_READ,
        handler=connector_api.connector_read,
    )
    ctx.register_tool(
        name="connector_sync",
        toolset="pc_apps",
        schema=schemas.CONNECTOR_SYNC,
        handler=connector_api.connector_sync,
    )
    ctx.register_tool(
        name="maps_eta",
        toolset="pc_apps",
        schema=schemas.MAPS_ETA,
        handler=maps_api.maps_eta,
    )
    ctx.register_tool(
        name="composio_status",
        toolset="pc_apps",
        schema=schemas.COMPOSIO_STATUS,
        handler=composio_api.composio_status,
    )
    ctx.register_tool(
        name="composio_connect",
        toolset="pc_apps",
        schema=schemas.COMPOSIO_CONNECT,
        handler=composio_api.composio_connect,
    )
    ctx.register_tool(
        name="composio_setup",
        toolset="pc_apps",
        schema=schemas.COMPOSIO_SETUP,
        handler=composio_api.composio_setup,
    )
